# https://hub.docker.com/_/ubuntu
image: ubuntu:18.04

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - cat /etc/lsb-release
  - DEBIAN_FRONTEND=noninteractive apt-get -yq update
  - DEBIAN_FRONTEND=noninteractive apt-get -yq install software-properties-common systemd openssh-client openssh-server
  - add-apt-repository -y ppa:deadsnakes/ppa
  - apt -yq purge google-chrome* || true
  - ls /etc/apt/sources.list.d
  - rm -Rf /etc/apt/sources.list.d/google-chrome.list || true
  - apt-get -yq update
  - DEBIAN_FRONTEND=noninteractive apt-get -yq install python3.9-minimal python3.9 python3.9-dev python3.9-venv python3-pip python3-setuptools
  - apt-get -yq purge postgr* || true
  - apt-get -yq purge virtualbox* || true
  - apt-get -yq purge oracle-java* || true

  - apt-get -yq install mysql-server
  - systemctl enable mysql
  - service mysql start
  - systemctl enable ssh
  - service ssh start
  - apt-get -o Dpkg::Options::="--force-confnew" --allow-downgrades --allow-remove-essential --allow-change-held-packages -fuy --allow-unauthenticated dist-upgrade
  - apt-get -yq install build-essential
  - update-alternatives --install /usr/bin/python python /usr/bin/python3.9 10
  #- apt-get -yq --allow-downgrades --allow-remove-essential --allow-change-held-packages install linux-headers-`uname -r`
  - python -V
  - python3.9 -m pip --version
  - python3.9 -m pip install -r requirements-test.txt

  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  # Creation of an SSH agent for testing forwarding
  - eval $(ssh-agent)
  - ssh-add

test:
  script:
  - python3.7 -m venv .env
  - ". .env/bin/activate"
  - "pip --version"
  - "pip install -r requirements-test.txt"
  - "pylint --version"
  - ./pep8.sh
  #- "tox -c tox-travis.ini -e py37-no_vagrant -- -s burlap/tests/test_pip.py::PipTests"
  -   tox -c tox-travis.ini -e py39-no_vagrant
